#! /bin/sh

set -e

URL_BASE="https://github.com/keyboardio/Chrysalis-Firmware-Bundle/releases"
TARBALL_FN="firmware-files.tar.gz"

TAG="$1"

if [ -z "${TAG}" ]; then
    TAG=$(curl -s -I "${URL_BASE}/latest" | grep "^location: " | sed -e "s,.*/releases/tag/,," | tr -d "\r\n")
fi

URL="${URL_BASE}/download/${TAG}/${TARBALL_FN}"

curl -s -L "${URL}" | tar -C static -xzf -
git add static/**/default.{hex,bin} static/firmware-changelog.md static/build-info.yml

TMP=$(mktemp)
cat >${TMP} <<EOF
Update the firmware files we ship with

Artifacts downloaded from keyboardio/Chrysalis-Firmware-Bundle@${TAG}.

$(head -n 17 static/release-notes.md | tail -n +3)
EOF
git commit -s -F "${TMP}"
rm -f "${TMP}" static/release-notes.md
