#! /bin/bash

set -e

travis() {
    curl -s "https://api.travis-ci.org${1}" -H "Travis-API-Version: 3"
}

urlencode() {
    echo "$1" | sed -e "s/+/%2B/g"
}

usage() {
    cat <<EOF
Usage: $0 [OPTIONS]

Available options are:
 -h                This help screen
 -b BRANCH         Set the branch to download an artifact from.
                   Defaults to "master".
 -n BUILD_NUMBER   The Travis build number to download the artifact for.
                   Defaults to the latest successful build on the selected branch.
 -e EXTENSION      The artifact extension.
                   Defaults to "amd64.appImage".
EOF
}

fetch_build_number() {
    REPO_ID=$(travis "/owner/keyboardio/repos" | jq '.repositories[] | select(.name == "Chrysalis") | .id')
    LAST_PASSED_BUILD=$(travis "/repo/${REPO_ID}/builds?state=passed&sort_by=id:desc" | jq -r ".builds[] | select(.branch.name == \"${TRAVIS_BRANCH}\") | .number" | head -n 1)
    BUILD_NUMBER=${LAST_PASSED_BUILD}

    echo ${BUILD_NUMBER}
}

optstring="hb:n:e:"

BRANCH=""
TRAVIS_BRANCH="master"
BUILD_NUMBER=""
EXTENSION="amd64.AppImage"

while getopts ${optstring} arg; do
    case "${arg}" in
        h)
            usage
            exit 0
            ;;
        b)
            if [ "${OPTARG}" = "master" ]; then
                BRANCH=""
            else
                BRANCH="${OPTARG}/"
            fi
            TRAVIS_BRANCH="${OPTARG}"
            ;;
        n)
            BUILD_NUMBER="${OPTARG}"
            ;;
        e)
            EXTENSION="${OPTARG}"
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done

echo -n "Fetching latest build number... "
if [ -z "${BUILD_NUMBER}" ]; then
    BUILD_NUMBER="$(fetch_build_number)"
fi
echo "${BUILD_NUMBER}"

echo -n "Fetching the version number... "
VERSION="$(curl -s -f https://kaleidoscope-builds.s3.amazonaws.com/Chrysalis/${BRANCH}${BUILD_NUMBER}/version.txt)"
echo "${VERSION}"

echo -n "Downloading to Chrysalis-${VERSION}.${EXTENSION}... "

curl -s -o Chrysalis-${VERSION}.${EXTENSION} \
     https://kaleidoscope-builds.s3.amazonaws.com/Chrysalis/${BRANCH}${BUILD_NUMBER}/Chrysalis-$(urlencode ${VERSION}).${EXTENSION}

echo "done."
