name: Build & publish pull request artifacts

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install udev-dev
        run: sudo apt update && sudo apt install libudev-dev
        if: runner.os == 'Linux'

      - name: Set up yarn network timeout
        run: yarn config set network-timeout 1000000 -g

      - name: Install Yarn dependencies
        env:
          YARN_GPG: no
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: yarn
      - name: Release (macos)
        if: matrix.os == 'macos-latest'
        env:
          UNTRUSTED: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:  yarn run publish --arch=universal --dry-run
      - name: Release (non-macos)
        if: matrix.os != 'macos-latest'
        env:
          UNTRUSTED: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:  yarn run publish --dry-run


      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-artifact
          path: |
            out/make/**/Chrysalis-*

  publish:
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: publish

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: artifacts
          message: |
            Build artifacts for this pull request are available!

            :warning: These are not official builds!
            ----------------------------------------

            The build artifacts are provided as-is, for testing and reviewing purposes. They contain code that has not been reviewed or audited by Chrysalis' developers. They are not endorsed by Keyboardio, they are not signed. Install and use them only if you know what you are doing.
            
            You can download the platform-specific build artifacts from GitHub for 90 days after the date of this message from the following URL:
            https://github.com/keyboardio/Chrysalis/actions/runs/${{ github.run_id }}#artifacts
